In [152]:
import numpy as np
from numpy.linalg import svd, pinv

In [146]:
m = 3
n = 5
J = np.random.rand(m, n)

In [164]:
u, s, vh = svd(pinv(J.T))

In [165]:
S = np.zeros_like(J)
S[:min(J.shape[0], J.shape[1]), :min(J.shape[0], J.shape[1])] = np.diag(s)
V = vh.conj().T
U = u

In [166]:
N_ = (np.eye(J.shape[1]) - np.dot(pinv(J), J))
x = np.random.rand(J.shape[1], 1)
np.allclose(np.dot(J, np.dot(N_,x)), np.zeros(J.shape[0]))

True

In [170]:
N = (np.eye(J.shape[1]) - np.dot(V, np.dot(np.dot(pinv(S), S), V.T)))
np.dot(J, N)

array([[-7.10065879e-16,  1.33854446e-15,  1.28801904e-16,
        -3.36522038e-16, -1.74428011e-16],
       [-5.78027022e-16,  1.10185973e-15,  9.32195599e-17,
        -6.71160727e-16,  1.98482094e-16],
       [-7.04164908e-16,  1.08628673e-15,  6.83126299e-17,
        -7.49818208e-17, -3.02961861e-16]])

In [159]:
u, s, vh = svd(J)
print('U:\n', u)
print('s: \n', s)
print('Vh: \v',vh)

U:
 [[-0.61584751  0.28664283 -0.73387175]
 [-0.6548776  -0.70410379  0.27454175]
 [-0.43802646  0.64967202  0.62133653]]
s: 
 [2.56150964 0.580055   0.21889061]
Vh:  [[-0.37896444 -0.35837682 -0.56950737 -0.56420944 -0.29202923]
 [-0.45427496  0.12177142 -0.00798327  0.58005402 -0.66504104]
 [ 0.71259165  0.32547053 -0.44790834 -0.01029111 -0.43076013]
 [ 0.2216968  -0.69251397 -0.3594227   0.54810419  0.20413733]
 [-0.30509651  0.52079854 -0.58804002  0.21137863  0.49518988]]


In [153]:
def nullspace(A, atol=1e-13, rtol=0):
    A = np.atleast_2d(A)
    u,s,vh = svd(A)
    tol = max(atol, rtol*s[0])
    nnz = (s >= tol).sum()
    ns = vh[nnz:].conj().T
    return ns

In [160]:
u, s, vh = svd(pinv(J.T))
print('U:\n', u)
print('s: \n', s)
print('Vh: \v',vh)

U:
 [[-0.73387175  0.28664283  0.61584751]
 [ 0.27454175 -0.70410379  0.6548776 ]
 [ 0.62133653  0.64967202  0.43802646]]
s: 
 [4.56849203 1.72397444 0.39039478]
Vh:  [[ 0.71259165  0.32547053 -0.44790834 -0.01029111 -0.43076013]
 [-0.45427496  0.12177142 -0.00798327  0.58005402 -0.66504104]
 [ 0.37896444  0.35837682  0.56950737  0.56420944  0.29202923]
 [ 0.15551057 -0.57306225 -0.4707778   0.57950003  0.29994015]
 [-0.34358378  0.64992797 -0.5033329   0.09632677  0.44375778]]
